apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
      matchLabels:
        app.kubernetes.io/name: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: urlshortener
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_PASSWORD
          value: urlshortener
        - name: POSTGRES_USER
          value: urlshortener
        image: postgres:12
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: urlshortener-pgdata
      restartPolicy: Always
      volumes:
      - name: urlshortener-pgdata
        persistentVolumeClaim:
          claimName: urlshortener-pgdata
status: {}
