version: '2'

services:
  pythonapp:
    container_name: pythonapp
    image: amirmraei/finalccproj
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://urlshortener:urlshortener@postgres:5432/urlshortener
    depends_on:
      - db
  
  db:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=urlshortener
      - POSTGRES_USER=urlshortener
      - POSTGRES_DB=urlshortener
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}