apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: pythonapp
  name: pythonapp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pythonapp
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://urlshortener:urlshortener@postgres:5432/urlshortener
        image: amirmraei/finaltry
        name: pythonapp
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
