apiVersion: "v1"
kind: Service
metadata:
  name: "flask-test"
  namespace: "default"
  labels:
    app: "flask-test"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  externalIPs:
    - 192.168.0.10
  selector:
    app: "flask-test"
  type: "LoadBalancer"
  loadBalancerIP: ""